version: '3.5'
services:
  icinga:
    image: edgd1er/rpi-icinga-nconf:latest
    build:
      dockerfile: Dockerfile.all
      context: .
      args:
        aptcache:
    restart: unless-stopped
    ports:
      - "8009:443"
    volumes:
      - ./archives/:/var/archives/
    environment:
      TZ: "Europe/Paris"
      REMOVE_OLDER_THAN: "120"
    env_file:
      - envMysql.icinga
      - envMsmtp.mine
    #networks:
    # - pihole_nginx-net
    tmpfs:
      - /var/log/icinga
      - /var/cache/icinga
    depends_on:
      - db

  db:
    image: mariadb/server
    ports:
      - 3326:3306
    restart:
      unless-stopped
    env_file:
      - envMysql
